name: test

on:
  push:
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    permissions:
      checks: write
    steps:
      - name: Harden Security
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm ci
      - run: pnpm test
      - run: pnpm lint
